[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
audioviz = "0.4.4"

simple_logger = "1.16.0"
log = "0.4.14"