#!/bin/sh

IP=raspberrypi
TARGET=armv7-unknown-linux-gnueabihf

read -sp 'Password: ' PASSWD

cargo build --release --target $TARGET

# upload binary
sshpass -p $PASSWD scp -r ./target/$TARGET/release/server pi@$IP:/home/pi

# execute binary
sshpass -p $PASSWD ssh -t pi@$IP './server'; 'killall server'
